/**
 * Namen-Pool für KI-Spieler.
 *
 * Beim Match-Start werden zufällig N Namen ausgewählt (ohne Doppelte). Die
 * Auswahl läuft über `Math.random()` — der Sim-PRNG bleibt davon unberührt,
 * weil Namen rein kosmetisch sind und keinen Spielablauf beeinflussen.
 *
 * Die Namen sind kuratiert bunt — kurze 1-Wort-Namen aus verschiedenen
 * Kulturkreisen, geschlechtsoffen, "Commander"-Atmosphäre.
 */

const COMMANDERS: readonly string[] = [
  'Cassius',
  'Lysandra',
  'Cyrus',
  'Tariq',
  'Yuki',
  'Bjorn',
  'Imhotep',
  'Helga',
  'Drogon',
  'Nikita',
  'Astrid',
  'Wendell',
  'Kano',
  'Sven',
  'Mara',
  'Rasmus',
  'Indira',
  'Kael',
  'Soren',
  'Nadia',
  'Theo',
  'Wren',
  'Felix',
  'Lyra',
  'Asa',
  'Ezra',
  'Iris',
  'Jules',
  'Quinn',
  'Ren',
  'Sage',
  'Tycho',
  'Vance',
  'Wynn',
  'Xavi',
  'Yara',
  'Zara',
  'Oren',
  'Pyre',
  'Mira',
  'Aldric',
  'Belen',
  'Cato',
  'Doran',
  'Eyra',
  'Floki',
  'Gunnar',
  'Hilde',
]

/** Chemische Elemente (international/englisch) — 'Gold' → 'Aurum' wegen der Spielwährung. */
const ELEMENTS: readonly string[] = [
  'Hydrogen',
  'Helium',
  'Lithium',
  'Beryllium',
  'Boron',
  'Carbon',
  'Nitrogen',
  'Oxygen',
  'Fluorine',
  'Neon',
  'Sodium',
  'Magnesium',
  'Aluminium',
  'Silicon',
  'Phosphorus',
  'Sulfur',
  'Chlorine',
  'Argon',
  'Potassium',
  'Calcium',
  'Scandium',
  'Titanium',
  'Vanadium',
  'Chromium',
  'Manganese',
  'Iron',
  'Cobalt',
  'Nickel',
  'Copper',
  'Zinc',
  'Gallium',
  'Germanium',
  'Arsenic',
  'Selenium',
  'Bromine',
  'Krypton',
  'Rubidium',
  'Strontium',
  'Yttrium',
  'Zirconium',
  'Niobium',
  'Molybdenum',
  'Technetium',
  'Ruthenium',
  'Rhodium',
  'Palladium',
  'Silver',
  'Cadmium',
  'Indium',
  'Tin',
  'Antimony',
  'Tellurium',
  'Iodine',
  'Xenon',
  'Caesium',
  'Barium',
  'Lanthanum',
  'Cerium',
  'Praseodymium',
  'Neodymium',
  'Promethium',
  'Samarium',
  'Europium',
  'Gadolinium',
  'Terbium',
  'Dysprosium',
  'Holmium',
  'Erbium',
  'Thulium',
  'Ytterbium',
  'Lutetium',
  'Hafnium',
  'Tantalum',
  'Tungsten',
  'Rhenium',
  'Osmium',
  'Iridium',
  'Platinum',
  'Aurum',
  'Mercury',
  'Thallium',
  'Lead',
  'Bismuth',
  'Polonium',
  'Astatine',
  'Radon',
  'Francium',
  'Radium',
  'Actinium',
  'Thorium',
  'Protactinium',
  'Uranium',
  'Neptunium',
  'Plutonium',
  'Americium',
  'Curium',
  'Berkelium',
  'Californium',
  'Einsteinium',
  'Fermium',
  'Mendelevium',
  'Nobelium',
  'Lawrencium',
  'Rutherfordium',
  'Dubnium',
  'Seaborgium',
  'Bohrium',
  'Hassium',
  'Meitnerium',
  'Darmstadtium',
  'Roentgenium',
  'Copernicium',
  'Nihonium',
  'Flerovium',
  'Moscovium',
  'Livermorium',
  'Tennessine',
  'Oganesson',
]

/** Berühmte Wissenschaftler (Nachnamen, sprach-neutral). */
const SCIENTISTS: readonly string[] = [
  'Newton',
  'Einstein',
  'Curie',
  'Darwin',
  'Tesla',
  'Galileo',
  'Kepler',
  'Hawking',
  'Feynman',
  'Planck',
  'Heisenberg',
  'Faraday',
  'Maxwell',
  'Pasteur',
  'Mendel',
  'Lovelace',
  'Turing',
  'Noether',
  'Hopper',
  'Franklin',
  'Dirac',
  'Pauli',
  'Boltzmann',
  'Avogadro',
  'Lavoisier',
  'Thomson',
  'Chadwick',
  'Compton',
  'Bose',
  'Raman',
  'Ramanujan',
  'Gauss',
  'Euler',
  'Riemann',
  'Hilbert',
  'Poincare',
  'Fibonacci',
  'Archimedes',
  'Pythagoras',
  'Euclid',
  'Brahe',
  'Hubble',
  'Sagan',
  'Goodall',
  'Hypatia',
  'Aristotle',
  'Democritus',
  'Vesalius',
  'Hooke',
  'Boyle',
  'Dalton',
  'Ohm',
  'Ampere',
  'Volta',
  'Joule',
  'Watt',
  'Kelvin',
  'Doppler',
  'Bernoulli',
  'Lagrange',
  'Laplace',
  'Fourier',
  'Cauchy',
  'Cantor',
  'Godel',
  'Shannon',
  'Wiener',
  'Mandelbrot',
  'Carson',
  'Lamarr',
  'Herschel',
  'Cavendish',
  'Galois',
  'Pascal',
  'Leibniz',
]

/**
 * Gesamter Namen-Pool: Commander-Namen + chemische Elemente + Wissenschaftler. Reicht für viele
 * hundert Nationen, bevor der „Nation N"-Fallback greift (wilde zeigen ohnehin nur „wild").
 */
const POOL: readonly string[] = [...COMMANDERS, ...ELEMENTS, ...SCIENTISTS]

/**
 * Wählt `count` Namen. Bis zur Pool-Größe eindeutige Zufallsnamen; werden mehr
 * verlangt (viele KI), wird mit generischen Namen ("Nation N") aufgefüllt.
 */
export function pickRandomNames(count: number): string[] {
  if (count < 0 || !Number.isInteger(count)) {
    throw new RangeError(`pickRandomNames: count must be a non-negative integer, got ${count}`)
  }
  const arr = [...POOL]
  // Fisher-Yates partial shuffle: nur so viele Slots randomisieren wie nötig
  const shuffleN = Math.min(count, arr.length)
  for (let i = 0; i < shuffleN; i++) {
    const j = i + Math.floor(Math.random() * (arr.length - i))
    const a = arr[i]
    const b = arr[j]
    if (a === undefined || b === undefined) {
      throw new Error('pickRandomNames: unexpected undefined during shuffle')
    }
    arr[i] = b
    arr[j] = a
  }
  const names = arr.slice(0, shuffleN)
  for (let n = names.length; n < count; n++) names.push(`Nation ${(n + 1).toString()}`)
  return names
}

/** Gesamtanzahl verfügbarer Namen — nützlich für UI-Konsistenz-Checks. */
export const NAME_POOL_SIZE = POOL.length
